
# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
# image: <your-workspace-image>
# Command to start on workspace startup (optional)
tasks:
  - command: python3 -m http.server 8080
    name: webserver
  - command: >
    name: terminal
# Ports to expose on workspace startup (optional)
ports:
  - port: 3000
    onOpen: notify
