
# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
# image: <your-workspace-image>
# Command to start on workspace startup (optional)
tasks:
  - command: python3 -m http.server 8000 -d web
    name: webserver
  - command: npx -y http-server -c-1 -p 8080 web
    name: webserver-nocache
  - command: >
    name: terminal
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
    onOpen: notify
